chore(deps): update dependency prettier to v2 (#5)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [prettier](https://prettier.io) ([source](https://togithub.com/prettier/prettier)) | devDependencies | major | [`^1.13.7` -> `^2.0.0`](https://renovatebot.com/diffs/npm/prettier/1.19.1/2.0.5) |

---

### Release Notes

<details>
<summary>prettier/prettier</summary>

### [`v2.0.5`](https://togithub.com/prettier/prettier/blob/master/CHANGELOG.md#&#8203;205)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.0.4...2.0.5)

[diff](https://togithub.com/prettier/prettier/compare/2.0.4...2.0.5)

##### Less: Fix formatting of `:extend` ([#&#8203;7984](https://togithub.com/prettier/prettier/pull/7984) by [@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```less
// Input
.class {
  &:extend(.some-class .some-other-class .some-very-loooooooooooooong-class all);
}

// Prettier 2.0.4
.class {
  &:extend(
    .some-class .some-other-class .some-very-loooooooooooooong-class all
  );
}

// Prettier 2.0.4 (Second format)
.class {
  &: extend(
    .some-class .some-other-class .some-very-loooooooooooooong-class all
  );
}

// Prettier 2.0.5
.class {
  &:extend(
    .some-class .some-other-class .some-very-loooooooooooooong-class all
  );
}
```

##### Editor integration: Use [`resolve`](https://www.npmjs.com/package/resolve) if builtin `require.resolve` is overridden ([#&#8203;8072](https://togithub.com/prettier/prettier/pull/8072) by [@&#8203;fisker](https://togithub.com/fisker))

This fixes issues that the users of Atom and WebStorm faced with 2.0.4.

Prettier now switches to using the `resolve` module for resolving configuration files and plugins if it detects that `require.resolve` isn't Node's builtin function (doesn't support the second argument), which happens in environments like editor extensions. To force the fallback, set the `PRETTIER_FALLBACK_RESOLVE` environment variable to `true`.

### [`v2.0.4`](https://togithub.com/prettier/prettier/blob/master/CHANGELOG.md#&#8203;204)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.0.3...2.0.4)

[diff](https://togithub.com/prettier/prettier/compare/2.0.3...2.0.4)

##### Revert [#&#8203;7869](https://togithub.com/prettier/prettier/pull/7869), "[TypeScript] format TSAsExpression with same logic as BinaryExpression" ([#&#8203;7958](https://togithub.com/prettier/prettier/pull/7958))

### [`v2.0.3`](https://togithub.com/prettier/prettier/blob/master/CHANGELOG.md#&#8203;203)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.0.2...2.0.3)

[diff](https://togithub.com/prettier/prettier/compare/2.0.2...2.0.3)

##### JavaScript

##### Fix `prettier-ignore` inside JSX ([#&#8203;7877](https://togithub.com/prettier/prettier/pull/7877) by [@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```jsx
// Input
<div>
{
  /* prettier-ignore */
  x     ?   <Y/> : <Z/>
}
</div>;

// Prettier 2.0.2 (first output)
<div>
  {/* prettier-ignore */
  x     ?   <Y/> : <Z/>}
</div>;

// Prettier 2.0.2 (second output)
<div>{/* prettier-ignore */ x     ?   <Y/> : <Z/>}</div>;

// Prettier 2.0.3
<div>
  {
    /* prettier-ignore */
    x     ?   <Y/> : <Z/>
  }
</div>;
```

##### Fix regressions in styled-components template literals ([#&#8203;7883](https://togithub.com/prettier/prettier/pull/7883) by [@&#8203;thorn0](https://togithub.com/thorn0))

<!-- prettier-ignore -->

```js
// Input
const Icon = styled.div`
  background:   var(--${background});
  ${Link}:not(:first-child) {
      fill:    rebeccapurple;
  }
`;

// Prettier 2.0.2
const Icon = styled.div`
  background: var(-- ${background});
  ${Link}:not (:first-child) {
    fill: rebeccapurple;
  }
`;

// Prettier 2.0.3
const Icon = styled.div`
  background: var(--${background});
  ${Link}:not(:first-child) {
    fill: rebeccapurple;
  }
`;
```

##### Fix: line endings were not always converted properly in multiline strings and comments ([#&#8203;7891](https://togithub.com/prettier/prettier/pull/7891) by [@&#8203;sidharthv96](https://togithub.com/sidharthv96))

<!-- prettier-ignore -->

    // Input
    export const IAmIncredibleLongFunctionName = IAmAnotherFunctionName(<CRLF>
      (_0: IAmIncredibleLongParameterType) => {<CRLF>
        setTimeout(() => {<CRLF>
          /*<CRLF>
            Multiline comment<CRLF>
            Multiline comment<CRLF>
            Multiline comment<CRLF>
          */<CRLF>
          console.log(<CRLF>
            "Multiline string\<CRLF>
             Multiline string\<CRLF>
             Multiline string"<CRLF>
          );<CRLF>
        });<CRLF>
      }<CRLF>
    );<CRLF>

    // Prettier 2.0.2
    export const IAmIncredibleLongFunctionName = IAmAnotherFunctionName(<CRLF>
      (_0: IAmIncredibleLongParameterType) => {<CRLF>
        setTimeout(() => {<CRLF>
          /*<LF>
            Multiline comment<LF>
            Multiline comment<LF>
            Multiline comment<LF>
          */<CRLF>
          console.log(<CRLF>
            "Multiline string\<LF>
             Multiline string\<LF>
             Multiline string"<CRLF>
          );<CRLF>
        });<CRLF>
      }<CRLF>
    );<CRLF>

    // Prettier 2.0.3: same as input

##### Fix bug with holes in array literals ([#&#8203;7911](https://togithub.com/prettier/prettier/pull/7911) by [@&#8203;bakkot](https://togithub.com/bakkot))

<!-- prettier-ignore -->

```jsx
// Input
new Test()
  .test()
  .test([, 0])
  .test();

// Prettier 2.0.2
[error] in.js: TypeError: Cannot read property 'type' of null

// Prettier 2.0.3
new Test().test().test([, 0]).test();
```

##### TypeScript

##### Wrap TSAsExpression ([#&#8203;7869](https://togithub.com/prettier/prettier/pull/7869) by [@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

<!-- prettier-ignore -->

```ts
// Input
const value = thisIsAnIdentifier as ThisIsAReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyLongInterface;

// Prettier 2.0.2
const value = thisIsAnIdentifier as ThisIsAReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyLongInterface;

// Prettier 2.0.3
const value =
  thisIsAnIdentifier as
  ThisIsAReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyLongInterface;
```

##### Flow

##### Print dangling comments for inexact object type ([#&#8203;7892](https://togithub.com/prettier/prettier/pull/7892) by [@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

<!-- prettier-ignore -->

```js
// Input
type Foo = {
  // comment
  ...,
};

// Prettier 2.0.2
Error: Comment "comment" was not printed. Please report this error!

// Prettier 2.0.3
type Foo = {
  // comment
  ...,
};
```

##### Do not add comma for explicit inexact object with indexer property or no properties ([#&#8203;7923](https://togithub.com/prettier/prettier/pull/7923) by [@&#8203;DmitryGonchar](https://togithub.com/DmitryGonchar))

<!-- prettier-ignore -->

```jsx
// Input
type T = {
  [string]: number,
  ...,
}

type T = {
  // comment
  ...,
}

// Prettier 2.0.2
type T = {
  [string]: number,
  ...,
}

type T = {
  // comment
  ...,
}

// Prettier 2.0.3
type T = {
  [string]: number,
  ...
}

type T = {
  // comment
  ...
}
```

##### HTML

##### Fix printing of ignored empty inline elements ([#&#8203;7867](https://togithub.com/prettier/prettier/pull/7867) by [@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```html
<!-- Input-->
<!--prettier-ignore--><span></span>
<!--prettier-ignore--><span>_</span>

<!-- Prettier 2.0.2 (first output) -->
<!--prettier-ignore--><span
></span>
<!--prettier-ignore--><span>_</span>

<!-- Prettier 2.0.2 (second output) -->
<!--prettier-ignore--><span

></span>
<!--prettier-ignore--><span>_</span>

<!-- Prettier 2.0.3 -->
<!--prettier-ignore--><span></span>
<!--prettier-ignore--><span>_</span>
```

##### Format `script` and `style` inside tags with a colon in the name ([#&#8203;7916](https://togithub.com/prettier/prettier/pull/7916) by [@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```html
<!-- Input -->
<with:colon>
<script>function foo(){      return 1}</script>
<style>a         {color:         #f00}</style>
</with:colon>

<!-- Prettier 2.0.2 -->
<with:colon>
  <script>
    function foo(){ return 1}
  </script>
  <style>
    a {color: #f00}
  </style>
</with:colon>

<!-- Prettier 2.0.3 -->
<with:colon>
  <script>
    function foo() {
      return 1;
    }
  </script>
  <style>
    a {
      color: #f00;
    }
  </style>
</with:colon>
```

##### Other changes

-   Workaround for `require.resolve` in prettier-vscode ([#&#8203;7951](https://togithub.com/prettier/prettier/pull/7951) by [@&#8203;thorn0](https://togithub.com/thorn0))
-   Fix unstable Angular expression binding ([#&#8203;7924](https://togithub.com/prettier/prettier/pull/7924) by [@&#8203;fisker](https://togithub.com/fisker))
-   Update `isSCSS` regex ([#&#8203;7922](https://togithub.com/prettier/prettier/pull/7922) by [@&#8203;fisker](https://togithub.com/fisker))
-   Fix formatting of empty files ([#&#8203;7921](https://togithub.com/prettier/prettier/pull/7921) by [@&#8203;fisker](https://togithub.com/fisker))

### [`v2.0.2`](https://togithub.com/prettier/prettier/blob/master/CHANGELOG.md#&#8203;202)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.0.1...2.0.2)

[diff](https://togithub.com/prettier/prettier/compare/2.0.1...2.0.2)

##### 2.0 regressions

##### JavaScript: Fix formatting of pseudo-elements and pseudo-classes in styled-components template literals ([#&#8203;7842](https://togithub.com/prettier/prettier/pull/7842) by [@&#8203;thorn0](https://togithub.com/thorn0))

<!-- prettier-ignore -->

```jsx
// Input
const Foo = styled.div`
  ${media.smallDown}::before {}
`;

// Prettier 2.0.0
const Foo = styled.div`
  ${media.smallDown}: : before{
  }
`;

// Prettier 2.0.2
const Foo = styled.div`
  ${media.smallDown}::before {
  }
`;
```

##### TypeScript: Avoid trailing commas on index signatures with only one parameter ([#&#8203;7836](https://togithub.com/prettier/prettier/pull/7836) by [@&#8203;bakkot](https://togithub.com/bakkot))

TypeScript index signatures technically allow multiple parameters and trailing commas, but it's an error to have multiple parameters there, and Babel's TypeScript parser does not accept them. So Prettier now avoids putting a trailing comma there when you have only one parameter.

<!-- prettier-ignore -->

```ts
// Input
export type A = {
  a?: {
    [
      x: string
    ]: typeof SomeLongLongLongTypeName[keyof typeof SomeLongLongLongTypeName];
  } | null;
};

// Prettier 2.0.0
export type A = {
  a?: {
    [
      x: string,
    ]: typeof SomeLongLongLongTypeName[keyof typeof SomeLongLongLongTypeName];
  } | null;
};

// Prettier 2.0.2
export type A = {
  a?: {
    [
      x: string
    ]: typeof SomeLongLongLongTypeName[keyof typeof SomeLongLongLongTypeName];
  } | null;
};
```

##### Revert "markdown: fix redundant leading spaces in markdown list" ([#&#8203;7847](https://togithub.com/prettier/prettier/pull/7847))

See [#&#8203;7846](https://togithub.com/prettier/prettier/issues/7846)

##### Other changes

##### TypeScript: Fix `prettier-ignore` in union types ([#&#8203;7798](https://togithub.com/prettier/prettier/pull/7798) by [@&#8203;thorn0](https://togithub.com/thorn0))

<!-- prettier-ignore -->

```ts
// Input
export type a =
  // foo
  | foo1&foo2
  // prettier-ignore
  | bar1&bar2
  // baz
  | baz1&baz2;

// Prettier 2.0.0
export type a =
  // foo
  | foo1&foo2
    // prettier-ignore
  // prettier-ignore
  | (bar1 & bar2)
  // baz
  | (baz1 & baz2);

// Prettier 2.0.2
export type a =
  // foo
  | (foo1 & foo2)
  // prettier-ignore
  | bar1&bar2
  // baz
  | (baz1 & baz2);
```

### [`v2.0.1`](https://togithub.com/prettier/prettier/blob/master/CHANGELOG.md#&#8203;201)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.0.0...2.0.1)

[diff](https://togithub.com/prettier/prettier/compare/2.0.0...2.0.1)

##### API: Fix build script to not corrupt `import-fresh` module ([#&#8203;7820](https://togithub.com/prettier/prettier/pull/7820) by [@&#8203;thorn0](https://togithub.com/thorn0))

### [`v2.0.0`](https://togithub.com/prettier/prettier/blob/master/CHANGELOG.md#&#8203;200)

[Compare Source](https://togithub.com/prettier/prettier/compare/1.19.1...2.0.0)

[diff](https://togithub.com/prettier/prettier/compare/1.19.1...2.0.0)

🔗 [Release Notes](https://prettier.io/blog/2020/03/21/2.0.0.html)

</details>

---

### Renovate configuration

:date: **Schedule**: "after 9am and before 3pm" (UTC).

:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

:recycle: **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

:no_bell: **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [WhiteSource Renovate](https://renovate.whitesourcesoftware.com). View repository job log [here](https://app.renovatebot.com/dashboard#googleapis/code-suggester).